### PR TITLE
fix 3

### PR DESCRIPTION
**Pull request by akisblack**

### CODE REVIEW

**Comment by Odyssey346** [comment]
Quick question: does this work in dev?

**Comment by akisblack** [comment]
thats the last thing you should care about

**Comment by Odyssey346** [comment]
But does it? Can you test?

**Comment by Odyssey346** [comment]
also goddamn I need to update my pfp on GitHub

**Comment by akisblack** [comment]
if you go to /blog it does work, otherwise it returns a 404 error

**Comment by Odyssey346** [comment]
Ah well let's see

**Comment by akisblack** [comment]
it literally works on local builds

**Pull request merged**
